version: "3.4"
services: 
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 aimvector/nodejs:1.0.0 /bin/sh
    container_name: nodejs
    image: aimvector/nodejs:1.0.0
    environment:
      NODE_ENV: production
      HOST: "0.0.0.0"
      PORT: 5000
      DB_HOST: db
    build:
      context: ./nodejs
      target: debug
    #working_dir: /work      #comment out for build.target:prod
    #entrypoint: /bin/sh     #comment out for build.target:prod
    #stdin_open: true        #comment out for build.target:prod
    #tty: true               #comment out for build.target:prod
    volumes:
    - ./nodejs/src/:/work/src/
    ports:
      - 5002:5000
      - 9229:9229            #debug port
    depends_on: 
      [db]
  db:
    container_name: mongodb
    image: mongo:4.2.5
    ports:
      - "27018:27017"
    volumes:
      - ./.data:/data/db